### ISSUE TITLE
AssertionFailure while moving a root node

### ISSUE THREAD

**Issue by endikag** [ticketbis/grails-nestedset#1]
When you try to move a previously saved root category or create a chid category I'm getting this error:

```
2015-12-30 15:30:12,660 ERROR                                                   
org.hibernate.AssertionFailure an assertion failure occured (this may indicate a bug in Hibernate, but is more likely due to unsafe use of the session)
org.hibernate.AssertionFailure: collection [entradia.AttendantType.eventos] was not processed by flush()
    at com.ticketbis.nestedset.NestedsetTrait$Trait$Helper.move_right(NestedsetTrait.groovy:268)
    at com.ticketbis.nestedset.NestedsetTrait$_Helper_moveNode_closure4.doCall(NestedsetTrait.groovy:380)
    at org.grails.datastore.gorm.GormStaticApi.withTransaction(GormStaticApi.groovy:815)
    at org.grails.datastore.gorm.GormStaticApi.withTransaction(GormStaticApi.groovy:715)
    at com.ticketbis.nestedset.NestedsetTrait$Trait$Helper.moveNode(NestedsetTrait.groovy:372)
    ...
```

**Comment by dhighwayman** [comment]
:+1:
